/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "../../packages/ui/src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "var(--theme-color-brand-50)",
          100: "var(--theme-color-brand-100)",
          200: "var(--theme-color-brand-200)",
          300: "var(--theme-color-brand-300)",
          400: "var(--theme-color-brand-400)",
          500: "var(--theme-color-brand-500)",
          600: "var(--theme-color-brand-600)",
          700: "var(--theme-color-brand-700)",
          800: "var(--theme-color-brand-800)",
          900: "var(--theme-color-brand-900)",
          950: "var(--theme-color-brand-950)",
        },
        "on-brand": "var(--theme-color-on-brand)",
        "on-success": "var(--theme-color-success-contrast)",
        "on-warning": "var(--theme-color-warning-contrast)",
        "on-danger": "var(--theme-color-danger-contrast)",
        secondary: {
          50: "var(--theme-color-neutral-50)",
          100: "var(--theme-color-neutral-100)",
          200: "var(--theme-color-neutral-200)",
          300: "var(--theme-color-neutral-300)",
          400: "var(--theme-color-neutral-400)",
          500: "var(--theme-color-neutral-500)",
          600: "var(--theme-color-neutral-600)",
          700: "var(--theme-color-neutral-700)",
          800: "var(--theme-color-neutral-800)",
          900: "var(--theme-color-neutral-900)",
          950: "var(--theme-color-neutral-950)",
        },
        accent: "var(--color-accent)",
        "accent-light": "var(--color-accent-light)",
        "background-light": "var(--color-bg-light)",
        "background-dark": "var(--color-bg-dark)",
        surface: "var(--color-surface)",
        "surface-alt": "var(--color-surface-alt)",
        success: {
          50: "var(--theme-color-success-50)",
          100: "var(--theme-color-success-100)",
          200: "var(--theme-color-success-200)",
          300: "var(--theme-color-success-300)",
          400: "var(--theme-color-success-400)",
          500: "var(--theme-color-success-500)",
          600: "var(--theme-color-success-600)",
          700: "var(--theme-color-success-700)",
          800: "var(--theme-color-success-800)",
          900: "var(--theme-color-success-900)",
          950: "var(--theme-color-success-950)",
          DEFAULT: "var(--theme-color-success-solid)",
        },
        warning: {
          50: "var(--theme-color-warning-50)",
          100: "var(--theme-color-warning-100)",
          200: "var(--theme-color-warning-200)",
          300: "var(--theme-color-warning-300)",
          400: "var(--theme-color-warning-400)",
          500: "var(--theme-color-warning-500)",
          600: "var(--theme-color-warning-600)",
          700: "var(--theme-color-warning-700)",
          800: "var(--theme-color-warning-800)",
          900: "var(--theme-color-warning-900)",
          950: "var(--theme-color-warning-950)",
          DEFAULT: "var(--theme-color-warning-solid)",
        },
        danger: {
          50: "var(--theme-color-danger-50)",
          100: "var(--theme-color-danger-100)",
          200: "var(--theme-color-danger-200)",
          300: "var(--theme-color-danger-300)",
          400: "var(--theme-color-danger-400)",
          500: "var(--theme-color-danger-500)",
          600: "var(--theme-color-danger-600)",
          700: "var(--theme-color-danger-700)",
          800: "var(--theme-color-danger-800)",
          900: "var(--theme-color-danger-900)",
          950: "var(--theme-color-danger-950)",
          DEFAULT: "var(--theme-color-danger-solid)",
        },
        info: {
          50: "var(--theme-color-info-50)",
          100: "var(--theme-color-info-100)",
          200: "var(--theme-color-info-200)",
          300: "var(--theme-color-info-300)",
          400: "var(--theme-color-info-400)",
          500: "var(--theme-color-info-500)",
          600: "var(--theme-color-info-600)",
          700: "var(--theme-color-info-700)",
          800: "var(--theme-color-info-800)",
          900: "var(--theme-color-info-900)",
          950: "var(--theme-color-info-950)",
          DEFAULT: "var(--theme-color-info-solid)",
        },
      },
      fontFamily: {
        display: [
          "var(--theme-font-display)",
          "Plus Jakarta Sans",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "var(--theme-font-body)",
          "Plus Jakarta Sans",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        navigation: "var(--theme-font-size-navigation)",
        xs: "var(--theme-font-size-caption)",
        sm: "var(--theme-font-size-body)",
        base: "var(--theme-font-size-body-lg)",
        lg: "var(--theme-font-size-card-title)",
        xl: "var(--theme-font-size-section-title)",
        "2xl": "var(--theme-font-size-page-title)",
        "3xl": "var(--theme-font-size-hero)",
        "4xl": "var(--theme-font-size-hero)",
        "5xl": "var(--theme-font-size-hero)",
        "6xl": "var(--theme-font-size-display)",
        "7xl": "var(--theme-font-size-display)",
        caption: "var(--theme-font-size-caption)",
        label: "var(--theme-font-size-label)",
        body: "var(--theme-font-size-body)",
        "body-lg": "var(--theme-font-size-body-lg)",
        "card-title": "var(--theme-font-size-card-title)",
        "section-title": "var(--theme-font-size-section-title)",
        "page-title": "var(--theme-font-size-page-title)",
        hero: "var(--theme-font-size-hero)",
        display: "var(--theme-font-size-display)",
      },
      fontWeight: {
        normal: "var(--theme-font-weight-regular)",
        medium: "var(--theme-font-weight-medium)",
        semibold: "var(--theme-font-weight-semibold)",
        bold: "var(--theme-font-weight-bold)",
      },
      letterSpacing: {
        tight: "var(--theme-letter-spacing-tight)",
        wide: "var(--theme-letter-spacing-wide)",
      },
      borderRadius: {
        DEFAULT: "var(--theme-radius-control)",
        sm: "var(--theme-radius-control)",
        md: "var(--theme-radius-control)",
        lg: "var(--theme-radius-control)",
        xl: "var(--theme-radius-panel)",
        "2xl": "var(--theme-radius-panel)",
        "3xl": "var(--theme-radius-dialog)",
        full: "var(--theme-radius-pill)",
      },
      boxShadow: {
        soft: "var(--theme-shadow-soft)",
        card: "var(--theme-shadow-card)",
        float: "var(--theme-shadow-float)",
        inset: "var(--theme-shadow-inset)",
      },
    },
  },
  plugins: [],
};
