using Application.Contracts.Report;

namespace Application.Features.Reports;

/// <summary>
/// Describes a report that can be generated by the reporting service.
/// </summary>
public sealed record ReportTypeDefinition
{
    /// <summary>The stable report identifier used in routes and requests.</summary>
    public required string Id { get; init; }

    /// <summary>The user-facing report name.</summary>
    public required string Name { get; init; }

    /// <summary>A short description of the report contents.</summary>
    public required string Description { get; init; }

    /// <summary>The report category shown in the Reports list.</summary>
    public required string Category { get; init; }

    /// <summary>The Material Symbols icon name shown in the Reports list.</summary>
    public string Icon { get; init; } = "description";

    /// <summary>The supported filters for this report.</summary>
    public IReadOnlyList<ReportFilter> Filters { get; init; } = Array.Empty<ReportFilter>();

    /// <summary>Default and configurability settings for report page size and orientation.</summary>
    public ReportPageSetupDefinition PageSetup { get; init; } = new();
}
