<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<!-- Additional settings specific to Auth project -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="jose-jwt" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.WsFederation" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" />
		<PackageReference Include="Sentry.AspNetCore" />
		<PackageReference Include="Sentry.OpenTelemetry" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
		<ProjectReference Include="..\..\BuildingBlocks\Validation\Validation.csproj" />
	</ItemGroup>

</Project>
