using Data.Data;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Domain.Services.Chat;

/// <summary>
/// Chat service implementation.
/// In production, wire to an LLM provider (Azure OpenAI, AWS Bedrock, etc.).
/// </summary>
public class ChatService : IChatService
{
    private readonly MainDbContext _context;
    private readonly ILogger<ChatService> _logger;

    public ChatService(MainDbContext context, ILogger<ChatService> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task<List<ChatConversation>> GetConversationsAsync(string userId, string? source = null)
    {
        var query = _context.Set<ChatConversation>()
            .Where(c => c.UserId == userId);

        if (!string.IsNullOrEmpty(source))
            query = query.Where(c => c.Source == source);

        return await query.OrderByDescending(c => c.LastMessageAt).ToListAsync();
    }

    public async Task<ChatConversation?> GetConversationAsync(int conversationId)
    {
        return await _context.Set<ChatConversation>()
            .Include(c => c.Messages.OrderByDescending(m => m.CreatedOn).Take(1))
            .FirstOrDefaultAsync(c => c.Id == conversationId);
    }

    public async Task<ChatConversation> CreateConversationAsync(string userId, string title, string source)
    {
        var conversation = new ChatConversation
        {
            UserId = userId,
            Title = title,
            Source = source,
            LastMessageAt = DateTime.UtcNow,
            MessageCount = 0
        };

        _context.Set<ChatConversation>().Add(conversation);
        await _context.SaveChangesAsync();
        return conversation;
    }

    public async Task DeleteConversationAsync(int conversationId)
    {
        var conversation = await _context.Set<ChatConversation>()
            .Include(c => c.Messages)
            .FirstOrDefaultAsync(c => c.Id == conversationId);

        if (conversation != null)
        {
            _context.Set<ChatMessage>().RemoveRange(conversation.Messages);
            _context.Set<ChatConversation>().Remove(conversation);
            await _context.SaveChangesAsync();
        }
    }

    public async Task RenameConversationAsync(int conversationId, string newTitle)
    {
        var conversation = await _context.Set<ChatConversation>().FindAsync(conversationId);
        if (conversation != null)
        {
            conversation.Title = newTitle;
            await _context.SaveChangesAsync();
        }
    }

    public async Task<List<ChatMessage>> GetMessagesAsync(int conversationId)
    {
        return await _context.Set<ChatMessage>()
            .Where(m => m.ConversationId == conversationId)
            .OrderBy(m => m.CreatedOn)
            .ToListAsync();
    }

    public async Task<ChatMessage> SendMessageAsync(int conversationId, string userId, string content)
    {
        var userMsg = new ChatMessage
        {
            ConversationId = conversationId,
            Role = "user",
            Content = content,
            TokenCount = content.Length / 4
        };

        _context.Set<ChatMessage>().Add(userMsg);

        // Placeholder AI response
        var assistantMsg = new ChatMessage
        {
            ConversationId = conversationId,
            Role = "assistant",
            Content = $"This is a placeholder AI response. In production, this would be generated by an LLM (Azure OpenAI, AWS Bedrock, etc.).\n\nYour message: _{content}_\n\nConfigure the AI provider in appsettings.json under `AI` section.",
            TokenCount = 50
        };

        _context.Set<ChatMessage>().Add(assistantMsg);

        // Update conversation metadata
        var conversation = await _context.Set<ChatConversation>().FindAsync(conversationId);
        if (conversation != null)
        {
            conversation.LastMessageAt = DateTime.UtcNow;
            conversation.MessageCount += 2;
        }

        await _context.SaveChangesAsync();
        return assistantMsg;
    }

    public async IAsyncEnumerable<string> StreamResponseAsync(int conversationId, string userId, string message)
    {
        // Save user message
        var userMsg = new ChatMessage
        {
            ConversationId = conversationId,
            Role = "user",
            Content = message,
            TokenCount = message.Length / 4
        };
        _context.Set<ChatMessage>().Add(userMsg);
        await _context.SaveChangesAsync();

        // Simulate streaming response
        var response = "👋 Hello! I'm the NIE Template AI assistant.\n\nThis is a **streaming** response demonstrating the SSE (Server-Sent Events) pattern used by the CDB chatbot.\n\nIn production:\n- Connect to Azure OpenAI, AWS Bedrock, or your preferred LLM\n- Enable pgvector for semantic search / RAG\n- Configure in `AI` section of appsettings.json";
        var words = response.Split(' ');

        var fullResponse = "";
        foreach (var word in words)
        {
            fullResponse += word + " ";
            yield return word + " ";
            await Task.Delay(30); // Simulate streaming latency
        }

        // Save assistant message
        var assistantMsg = new ChatMessage
        {
            ConversationId = conversationId,
            Role = "assistant",
            Content = fullResponse.Trim(),
            TokenCount = fullResponse.Length / 4
        };
        _context.Set<ChatMessage>().Add(assistantMsg);

        var conversation = await _context.Set<ChatConversation>().FindAsync(conversationId);
        if (conversation != null)
        {
            conversation.LastMessageAt = DateTime.UtcNow;
            conversation.MessageCount += 2;
        }

        await _context.SaveChangesAsync();
    }
}
