// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260428034115_ApprovalStageEnum")]
    partial class ApprovalStageEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AccessFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemFunction")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Type", "Module", "DisplayOrder");

                    b.ToTable("AccessFunctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "screen.dashboard.view",
                            Description = "Open the main staff dashboard shell.",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Dashboard",
                            Name = "View dashboard",
                            ResourceName = "dashboard",
                            Route = "/",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "screen.operations.view",
                            Description = "Open the operations list and detail workflow.",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Operations",
                            Name = "View operations list",
                            ResourceName = "operations",
                            Route = "/operations",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "screen.reports.view",
                            Description = "Open reporting and dashboard summaries.",
                            DisplayOrder = 30,
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Reporting",
                            Name = "View reports",
                            ResourceName = "reports",
                            Route = "/reports",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "screen.audit.view",
                            Description = "Open the audit log management screen.",
                            DisplayOrder = 40,
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Audit",
                            Name = "View audit trail",
                            ResourceName = "audit",
                            Route = "/audit",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "screen.access-control.view",
                            Description = "Open the access control administration screen.",
                            DisplayOrder = 50,
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Administration",
                            Name = "View access control",
                            ResourceName = "access-control",
                            Route = "/access-control",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "api.code.read",
                            Description = "Read code-table and lookup data.",
                            DisplayOrder = 100,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Reference Data",
                            Name = "Read code tables",
                            ResourceName = "CodeController.GetAll",
                            Route = "/api/Code",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "api.document.download",
                            Description = "Download stored documents.",
                            DisplayOrder = 130,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Documents",
                            Name = "Download documents",
                            ResourceName = "DocumentController.DownloadFile",
                            Route = "/api/Document/DownloadFile",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "api.document.manage",
                            Description = "Upload or delete stored documents.",
                            DisplayOrder = 140,
                            HttpMethod = "POST",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Documents",
                            Name = "Manage documents",
                            ResourceName = "DocumentController.UploadFile/DeleteFile",
                            Route = "/api/Document",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "api.audit-log.read",
                            Description = "Read audit history, summaries, and entity change details.",
                            DisplayOrder = 150,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Audit",
                            Name = "Read audit logs",
                            ResourceName = "AuditLogController.Get*",
                            Route = "/api/AuditLog",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Code = "api.access-control.read",
                            Description = "Read roles, assignments, and access function configuration.",
                            DisplayOrder = 160,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Administration",
                            Name = "Read access control",
                            ResourceName = "AccessControlController.Get*",
                            Route = "/api/AccessControl",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Code = "api.access-control.roles.manage",
                            Description = "Create, update, or delete roles and their access functions.",
                            DisplayOrder = 170,
                            HttpMethod = "POST/DELETE",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Administration",
                            Name = "Manage roles",
                            ResourceName = "AccessControlController.CreateRole/UpdateRole/DeleteRole",
                            Route = "/api/AccessControl",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "api.access-control.assignments.manage",
                            Description = "Assign or remove roles for users.",
                            DisplayOrder = 180,
                            HttpMethod = "POST/DELETE",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Administration",
                            Name = "Manage role assignments",
                            ResourceName = "AccessControlController.AssignRole/RemoveAssignment",
                            Route = "/api/AccessControl",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Code = "api.procurement.vendor.read",
                            Description = "Read vendor records.",
                            DisplayOrder = 200,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Read vendors",
                            ResourceName = "VendorController.Get*",
                            Route = "/api/Vendor",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Code = "api.procurement.vendor.manage",
                            Description = "Create, update, or delete vendor records.",
                            DisplayOrder = 210,
                            HttpMethod = "POST",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Manage vendors",
                            ResourceName = "VendorController.Save/Edit/Delete*",
                            Route = "/api/Vendor",
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Code = "api.procurement.catalog.read",
                            Description = "Read catalog item records.",
                            DisplayOrder = 220,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Read catalog items",
                            ResourceName = "CatalogItemController.Get*",
                            Route = "/api/CatalogItem",
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Code = "api.procurement.catalog.manage",
                            Description = "Create, update, or delete catalog items.",
                            DisplayOrder = 230,
                            HttpMethod = "POST",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Manage catalog items",
                            ResourceName = "CatalogItemController.Save/Edit/Delete*",
                            Route = "/api/CatalogItem",
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Code = "api.procurement.order.read",
                            Description = "Read purchase order records.",
                            DisplayOrder = 240,
                            HttpMethod = "GET",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Read purchase orders",
                            ResourceName = "PurchaseOrderController.Get*",
                            Route = "/api/PurchaseOrder",
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Code = "api.procurement.order.manage",
                            Description = "Create, update, or delete purchase orders.",
                            DisplayOrder = 250,
                            HttpMethod = "POST",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Manage purchase orders",
                            ResourceName = "PurchaseOrderController.Save/Edit/Delete*",
                            Route = "/api/PurchaseOrder",
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            Code = "api.procurement.order.approve",
                            Description = "Approve or reject submitted purchase orders.",
                            DisplayOrder = 260,
                            HttpMethod = "POST",
                            IsActive = true,
                            IsSystemFunction = true,
                            Module = "Procurement",
                            Name = "Approve purchase orders",
                            ResourceName = "PurchaseOrderController.Approve/Reject",
                            Route = "/api/PurchaseOrder",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ChangedProperties")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Category");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("SessionId");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("Category", "Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.HasIndex("Severity", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("Domain.Models.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DisplayName = "Mr.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "MR",
                            Type = "TITLE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DisplayName = "Mrs.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "MRS",
                            Type = "TITLE"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DisplayName = "Administrator",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "ADMIN",
                            Type = "USER_TYPE"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            DisplayName = "Non-Admin User",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "USER",
                            Type = "USER_TYPE"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            DisplayName = "IT Services",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "IT_SERVICES",
                            Type = "VENDOR_CATEGORY"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            DisplayName = "Office Supplies",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "OFFICE_SUPPLIES",
                            Type = "VENDOR_CATEGORY"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            DisplayName = "Maintenance",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "MAINTENANCE",
                            Type = "VENDOR_CATEGORY"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            DisplayName = "Consulting",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "CONSULTING",
                            Type = "VENDOR_CATEGORY"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            DisplayName = "Logistics",
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "LOGISTICS",
                            Type = "VENDOR_CATEGORY"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            DisplayName = "Hardware",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "HARDWARE",
                            Type = "CATALOG_CATEGORY"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            DisplayName = "Software",
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "SOFTWARE",
                            Type = "CATALOG_CATEGORY"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            DisplayName = "Furniture",
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "FURNITURE",
                            Type = "CATALOG_CATEGORY"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            DisplayName = "Stationery",
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "STATIONERY",
                            Type = "CATALOG_CATEGORY"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            DisplayName = "Cleaning",
                            DisplayOrder = 14,
                            IsActive = true,
                            Name = "CLEANING",
                            Type = "CATALOG_CATEGORY"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            DisplayName = "Each",
                            DisplayOrder = 15,
                            IsActive = true,
                            Name = "EACH",
                            Type = "UNIT_OF_MEASURE"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            DisplayName = "Box",
                            DisplayOrder = 16,
                            IsActive = true,
                            Name = "BOX",
                            Type = "UNIT_OF_MEASURE"
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            DisplayName = "Pack",
                            DisplayOrder = 17,
                            IsActive = true,
                            Name = "PACK",
                            Type = "UNIT_OF_MEASURE"
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            DisplayName = "Set",
                            DisplayOrder = 18,
                            IsActive = true,
                            Name = "SET",
                            Type = "UNIT_OF_MEASURE"
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            DisplayName = "Hour",
                            DisplayOrder = 19,
                            IsActive = true,
                            Name = "HOUR",
                            Type = "UNIT_OF_MEASURE"
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            DisplayName = "Main Office",
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "MAIN_OFFICE",
                            Type = "DELIVERY_LOCATION"
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            DisplayName = "Warehouse",
                            DisplayOrder = 21,
                            IsActive = true,
                            Name = "WAREHOUSE",
                            Type = "DELIVERY_LOCATION"
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            DisplayName = "Branch Office",
                            DisplayOrder = 22,
                            IsActive = true,
                            Name = "BRANCH_OFFICE",
                            Type = "DELIVERY_LOCATION"
                        },
                        new
                        {
                            Id = 23,
                            Description = "",
                            DisplayName = "SGD - Singapore Dollar",
                            DisplayOrder = 23,
                            IsActive = true,
                            Name = "SGD",
                            Type = "CURRENCY"
                        },
                        new
                        {
                            Id = 24,
                            Description = "",
                            DisplayName = "USD - US Dollar",
                            DisplayOrder = 24,
                            IsActive = true,
                            Name = "USD",
                            Type = "CURRENCY"
                        });
                });

            modelBuilder.Entity("Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerType")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedByName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovalStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApproverId")
                        .HasColumnType("text");

                    b.Property<string>("ApproverName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderApprovals");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDocuments");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CatalogItemId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SYSTEM_ADMIN",
                            Description = "Full access to screens, APIs, audit logs, and access control administration.",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OPERATIONS_MANAGER",
                            Description = "Manage operational records and review audit activity without changing access control.",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Operations Manager"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OPERATIONS_USER",
                            Description = "Work on operational records and document actions in the staff workspace.",
                            DisplayOrder = 30,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Operations User"
                        },
                        new
                        {
                            Id = 4,
                            Code = "READ_ONLY_VIEWER",
                            Description = "Read-only access to dashboards, reporting, and entity details.",
                            DisplayOrder = 40,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Read Only Viewer"
                        });
                });

            modelBuilder.Entity("Domain.Models.RoleAccessFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessFunctionId");

                    b.HasIndex("RoleId", "AccessFunctionId")
                        .IsUnique();

                    b.ToTable("RoleAccessFunctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFunctionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessFunctionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessFunctionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccessFunctionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccessFunctionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccessFunctionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            AccessFunctionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            AccessFunctionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            AccessFunctionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            AccessFunctionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            AccessFunctionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            AccessFunctionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            AccessFunctionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            AccessFunctionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            AccessFunctionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            AccessFunctionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            AccessFunctionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            AccessFunctionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            AccessFunctionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            AccessFunctionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            AccessFunctionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            AccessFunctionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            AccessFunctionId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            AccessFunctionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            AccessFunctionId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            AccessFunctionId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            AccessFunctionId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            AccessFunctionId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            AccessFunctionId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 30,
                            AccessFunctionId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 31,
                            AccessFunctionId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            AccessFunctionId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 33,
                            AccessFunctionId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 34,
                            AccessFunctionId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            AccessFunctionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            AccessFunctionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            AccessFunctionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            AccessFunctionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            AccessFunctionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            AccessFunctionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            AccessFunctionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            AccessFunctionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            AccessFunctionId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            AccessFunctionId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 45,
                            AccessFunctionId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 46,
                            AccessFunctionId = 6,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 47,
                            AccessFunctionId = 7,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 48,
                            AccessFunctionId = 13,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 49,
                            AccessFunctionId = 15,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            AccessFunctionId = 17,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleId = 1,
                            UserId = "xyfong"
                        },
                        new
                        {
                            Id = 2,
                            AssignedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleId = 1,
                            UserId = "devia"
                        });
                });

            modelBuilder.Entity("Domain.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.HasIndex("Function", "Expression")
                        .HasDatabaseName("IX_Function_Expression");

                    b.ToTable("CronTickers", "ticker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LockHolder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "ticker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExecutionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LockHolder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<int?>("RunCondition")
                        .HasColumnType("integer");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "ticker");
                });

            modelBuilder.Entity("Domain.Models.CatalogItem", b =>
                {
                    b.HasOne("Domain.Models.Vendor", "Vendor")
                        .WithMany("CatalogItems")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Domain.Models.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderApproval", b =>
                {
                    b.HasOne("Domain.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Approvals")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderDocument", b =>
                {
                    b.HasOne("Domain.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Documents")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("Domain.Models.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId");

                    b.HasOne("Domain.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Domain.Models.RoleAccessFunction", b =>
                {
                    b.HasOne("Domain.Models.AccessFunction", "AccessFunction")
                        .WithMany("RoleAccessFunctions")
                        .HasForeignKey("AccessFunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Role", "Role")
                        .WithMany("RoleAccessFunctions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessFunction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Models.UserRole", b =>
                {
                    b.HasOne("Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.TimeTickerEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.AccessFunction", b =>
                {
                    b.Navigation("RoleAccessFunctions");
                });

            modelBuilder.Entity("Domain.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Models.Role", b =>
                {
                    b.Navigation("RoleAccessFunctions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Models.Vendor", b =>
                {
                    b.Navigation("CatalogItems");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
